version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./docs:/docs
            - ./config/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./docs:/docs
        networks:
            - code-network

networks:
    code-network:
        driver: bridge